---
- name: download google key
  command: >
    wget -O /root/google.pub https://dl.google.com/linux/linux_signing_key.pub
  args:
    creates: /root/google.pub
  sudo: yes
  register: result_download_key
  until: result_download_key|success
